"""
This script takes the relevant svg code from the file generated by illustrator and places it inside the index.html file.abs
"""

def extractCode(filePath, groupNames):
    """
    Extract the relevant svg code from the file generated by illustrator, returning it as a list of lines.
    """
    # Initialising list of lines to be returned
    relevantCode = []

    # Copying is true when inside an important group
    copying = False

    # List of opening group tags that want to be copied
    for name in groupNames:
        groupTags.append('<g id="' + name + '">') 

    # Loop through each line of the svg file.
    with open(filePath) as infile:
        for line in infile:
            if not copying:
                # Check for line being an important group's opening
                if line.strip() in groupTags:
                    copying = True
                    innerGroupCount = 0
            else:
                # Check for inner group opening
                if line.strip()[:2] == "<g":
                    innerGroupCount += 1
                
                # Check for closing of group tag
                elif line.strip()[:3] == "</g":
                    # Check for the actual group closing
                    if innerGroupCount == 0:
                        copying = False
                        # APPEND? not sure
                    else:
                        innerGroupCount -= 1
                
                # Read line in if nothing else
                else:
                    relevantCode.append(line)